### ISSUE TITLE
RuntimeError: mat1 and mat2 shapes cannot be multiplied (32x73728 and 25088x12544)

### ISSUE THREAD

**Issue by wqlcaq** [erprogs/GenConViT#14]
python train.py --d ./data/data --m vae -e 30 -t y  (erro)
 Why does this error occur when running this instruction, but not when using another instruction (python train.py --d ./data/data --m ed -e 30 -t y -b 16)? This is an error that occurred during my training on ff+. May I ask if training the model for 30 epochs can achieve the effect mentioned in the article. Hope to receive a reply as soon as possible

python train.py --d ./data/data --m vae -e 30 -t y
Loading data...
Done.
/root/miniconda3/envs/GenConViT-main/lib/python3.8/site-packages/torch/functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3483.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
Traceback (most recent call last):
  File "train.py", line 208, in <module>
    main()
  File "train.py", line 202, in main
    train_model(path, mod, epoch, pretrained_model_filename, test_model, batch_size)
  File "train.py", line 72, in train_model
    train_loss, train_acc, epoch_loss = train(
  File "/root/autodl-tmp/GenConViT-main/GenConViT-main/train/train_vae.py", line 22, in train
    output, recons = model(images)
  File "/root/miniconda3/envs/GenConViT-main/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/autodl-tmp/GenConViT-main/GenConViT-main/model/genconvit_vae.py", line 108, in forward
    z = self.encoder(x)
  File "/root/miniconda3/envs/GenConViT-main/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/autodl-tmp/GenConViT-main/GenConViT-main/model/genconvit_vae.py", line 55, in forward
    mu =  self.mu(x)
  File "/root/miniconda3/envs/GenConViT-main/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/envs/GenConViT-main/lib/python3.8/site-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: mat1 and mat2 shapes cannot be multiplied (32x73728 and 25088x12544)

**Comment by daisy-12138** [comment]
我也碰到了，现在解决了，是因为输入图像的大小不是224x224，需要在dataset/loader.py中修改输入图像的大小为224x224
